### ISSUE TITLE
Issues with searching

### ISSUE THREAD

**Issue by pratik037** [Bernardi23/search_map_place#1]
The searchBox comes up on the screen, but places don't show up according to the search query.
If you want, I can share screenshot of the problem.
Hope it gets fixed soon.

**Comment by Bernardi23** [comment]
Which OS are you on (Android or iOS)? Can you post the code here? Are there any errors on the console? Also, please post a screenshot

**Comment by pratik037** [comment]
Currently tried on Android OS (Nougat). 
Here's the screenshot: 
![XhCj6HFd](https://user-images.githubusercontent.com/32771322/58872190-1d5e6580-86e1-11e9-930c-1234ecd1a131.jpg)

**Comment by pratik037** [comment]
Here's the code
[https://gist.github.com/pratik037/7965e2f1791837c5ae7f6c0ca8699d40](url)

**Comment by pratik037** [comment]
Here's the code

``` Dart
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:location/location.dart';
import 'package:search_map_place/search_map_place.dart';

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  
  Completer<GoogleMapController> _controller = Completer();
  
  static LatLng _target = LatLng(12.9351, 77.6084);
  
  final CameraPosition _initialCamera =
      CameraPosition(target: _target, zoom: 17);
  
  Location location = Location();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(children: <Widget>[
        GoogleMap(
          zoomGesturesEnabled: true,
          myLocationEnabled: true,
          myLocationButtonEnabled: true,
          compassEnabled: true,
          rotateGesturesEnabled: true,
          scrollGesturesEnabled: true,
          tiltGesturesEnabled: true,
          // markers: _markers,
          initialCameraPosition: _initialCamera,
          onMapCreated: (GoogleMapController controller) async {
            _controller.complete(controller);
            var pos = await location.getLocation();
            controller.animateCamera(CameraUpdate.newCameraPosition(
                CameraPosition(
                    target: LatLng(pos.latitude, pos.longitude), zoom: 17)));
            // _animateToUser();
            // SearchResult();
          },
        ),
        Positioned(
          top: 60,
          left: MediaQuery.of(context).size.width * 0.05,
          child: SearchMapPlaceWidget(
            //removed api key before making the gist
            apiKey: "",
            location: _initialCamera.target,
            radius: 30000,
            onSelected: (place) async {
              final geoloc = await place.geolocation;
              print("Geolocation data: " + geoloc.toString());

              final GoogleMapController _mapController =
                  await _controller.future;

                  print(geoloc.coordinates.toString());

              _mapController
                  .animateCamera(CameraUpdate.newLatLng(geoloc.coordinates));
              _mapController.animateCamera(
                  CameraUpdate.newLatLngBounds(geoloc.bounds, 0));
            },
          ),
        )
      ]),
    );
  }

  // _animateToUser() async {
  //   var pos = await location.getLocation();

  //   _control.animateCamera(CameraUpdate.newCameraPosition(
  //       CameraPosition(target: LatLng(pos.latitude, pos.longitude), zoom: 17)));
  // }
}
```

**Comment by Bernardi23** [comment]
Can I get a log of the console when you run the code and when you type something on the Input?

**Comment by pratik037** [comment]
> Can I get a log of the console when you run the code and when you type something on the Input?

Okay sure, gimme sometime I'll share it here

**Comment by pratik037** [comment]
@Bernardi23  If you can let me know how to get the exact log that you want, it'll be more helpful to you and much easier for me too?

**Comment by pratik037** [comment]
**When the app loads for debugging:**

```
Launching lib/main.dart on Redmi 4A in debug mode...

Built build/app/outputs/apk/debug/app-debug.apk.

W/ResourceType( 1607): No package identifier when getting name for resource number 0x00000000

I/zzbz    ( 1607): Making Creator dynamically

I/DynamiteModule( 1607): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:221

I/DynamiteModule( 1607): Selected remote version of com.google.android.gms.maps_dynamite, version >= 221

V/DynamiteModule( 1607): Dynamite loader version >= 2, using loadModule2NoCrashUtils

W/System  ( 1607): ClassLoader referenced unknown path:

D/ApplicationLoaders( 1607): ignored Vulkan layer search path /data/app/com.google.android.gms-2/lib/arm64:/data/app/com.google.android.gms-2/base.apk!/lib/arm64-v8a for namespace 0x7f8e664160

W/ResourceType( 1607): No package identifier when getting name for resource number 0x00000000

W/ChimeraDebugLogger( 1607): Singleton logger instance not set.

W/System  ( 1607): ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/0000009b/n/arm64-v8a

W/ResourceType( 1607): No package identifier when getting name for resource number 0x00000000

I/Google Maps Android API( 1607): Google Play services client version: 12451000

I/Google Maps Android API( 1607): Google Play services package version: 17455020

D/NetworkSecurityConfig( 1607): No Network Security Config specified, using platform default

W/Adreno-ES20( 1607): <get_gpu_clk:229>: open failed: errno 13

W/art     ( 1607): Suspending all threads took: 13.004ms

I/art     ( 1607): Background partial concurrent mark sweep GC freed 26178(3MB) AllocSpace objects, 23(1672KB) LOS objects, 52% free, 7MB/15MB, paused 14.446ms total 133.939ms

W/DynamiteModule( 1607): Local module descriptor class for com.google.android.gms.googlecertificates not found.

I/DynamiteModule( 1607): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:4

I/DynamiteModule( 1607): Selected remote version of com.google.android.gms.googlecertificates, version >= 4

W/ChimeraDebugLogger( 1607): Singleton logger instance not set.

W/System  ( 1607): ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/0000009a/n/arm64-v8a

W/ResourceType( 1607): No package identifier when getting name for resource number 0x00000000

```
**When Clicked on search bar and wrote some text :**
```
V/BoostFramework( 1607): BoostFramework() : mPerf = com.qualcomm.qti.Performance@ae0b9fa
W/ResourceType( 1607): No package identifier when getting name for resource number 0x00000000
```


*But I think you need some other kind of log, which i surely don't know how to access. Let me know what to do to get the logs.*

**Comment by Bernardi23** [comment]
Okay, first, I'll ask you to completely remove the "location" package out of you app (even from the pubscpec.yaml) then fully restart the app. The reason for that is that this package keeps giving me connection errors, so that might be a problem for you aswell (as a matter of fact, if I try to run with this package in my emulator, I have to fully delete the emulator, because all the apps have connection errors). Also, trying on another device would also be great.

If that doesn't work still, we will try to figure out something else

**Comment by pratik037** [comment]
> Okay, first, I'll ask you to completely remove the "location" package out of you app (even from the pubscpec.yaml) then fully restart the app. The reason for that is that this package keeps giving me connection errors, so that might be a problem for you aswell (as a matter of fact, if I try to run with this package in my emulator, I have to fully delete the emulator, because all the apps have connection errors). Also, trying on another device would also be great.
> 
> If that doesn't work still, we will try to figure out something else

Actually the location package is important to fetch the current location and show the blue dot on the map of the current location. If the *location* package should be removed by all means, then can you suggest some work around for that? 
Also, I think connection issue maybe because of the internet permissions in the *AndroidManifest.xml* file? (Just confirming)

**Comment by pratik037** [comment]
This is what I am talking about.
*Ignore the bottom navigation bar.*
**The blue location circle is mandatory requirement for the app**

![WhatsApp Image 2019-06-06 at 10 13 29 AM](https://user-images.githubusercontent.com/32771322/59007407-ddfc5a00-8843-11e9-9a75-d3d7f9e6fffe.jpeg)

**Comment by Bernardi23** [comment]
I know that the location package is important, but there are other packages that does the same thing. For now, I want you to remove it just for debugging purposes. I can't really help you if I can't reproduce this issue (which is the case with this package, like I said)

**Comment by pratik037** [comment]
> I know that the location package is important, but there are other packages that does the same thing. For now, I want you to remove it just for debugging purposes. I can't really help you if I can't reproduce this issue (which is the case with this package, like I said)

So I tried it without location package and with location package. In both the cases, its working. I think the issue was PlacesAPI, disabled it and then enabled it.

**Comment by pratik037** [comment]
@Bernardi23 **Thanks a lot for the support.** 
Also, can you share code for that zoom-in zoom out when a location is selected?
It'll be a great help.

**Comment by pratik037** [comment]
This is log of clicking on searchbar and selecting a place. Is it some kind of issue?

```
E/flutter (16349): #6      _SearchMapPlaceWidgetState._placeOption.<anonymous closure> 
package:search_map_place/src/searchMapPlaceWidget.dart:156
E/flutter (16349): #7      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:635
E/flutter (16349): #8      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:711
E/flutter (16349): #9      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:181
E/flutter (16349): #10     TapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:352
E/flutter (16349): #11     TapGestureRecognizer.handlePrimaryPointer 
package:flutter/…/gestures/tap.dart:264
E/flutter (16349): #12     PrimaryPointerGestureRecognizer.handleEvent 
package:flutter/…/gestures/recognizer.dart:450
E/flutter (16349): #13     PointerRouter._dispatch 
package:flutter/…/gestures/pointer_router.dart:73
E/flutter (16349): #14     PointerRouter.route 
package:flutter/…/gestures/pointer_router.dart:100
E/flutter (16349): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:218
E/flutter (16349): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
E/flutter (16349): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
E/flutter (16349): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
E/flutter (16349): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
E/flutter (16349): #20     _rootRunUnary  (dart:async/zone.dart:1136:13)
E/flutter (16349): #21     _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
E/flutter (16349): #22     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:931:7)
E/flutter (16349): #23     _invoke1  (dart:ui/hooks.dart:234:10)
E/flutter (16349): #24     _dispatchPointerDataPacket  (dart:ui/hooks.dart:154:5)
```

**Comment by Bernardi23** [comment]
Great! 

The code for the zoom is in the last example of the documentation. But here's the code:
```dart
final geolocation = await place.geolocation;

// Will animate the GoogleMap camera, taking us to the selected position with an appropriate zoom
final GoogleMapController controller = await _mapController.future;
controller.animateCamera(CameraUpdate.newLatLng(geolocation.coordinates));
controller.animateCamera(CameraUpdate.newLatLngBounds(geolocation.bounds, 0));
```

**Comment by pratik037** [comment]
@Bernardi23 Did this, but it doesn't seem to work. Again some dependency issue?
``` Dart
onSelected: (place) async {
              final geoloc = await place.geolocation;
              final GoogleMapController _mapController =
                  await _controller.future;
              _mapController
                  .animateCamera(CameraUpdate.newLatLng(geoloc.coordinates));
              _mapController.animateCamera(
                  CameraUpdate.newLatLngBounds(geoloc.bounds, 0));
            },
```

**Comment by Bernardi23** [comment]
That should work... Try printing `geoloc.coordinates` and `geoloc.bounds` to see if you're getting results. If you are, than it should be a problem with the GoogleMap widget itself, since all we're doing is using its controller to animate it.

**Comment by pratik037** [comment]
On trying
 ```Dart 
debugPrint('Coordinates: ' + geoloc.coordinates.toString());
 ```
**Result**
```Dart
W/IInputConnectionWrapper( 5874): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 5874): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 5874): getTextAfterCursor on inactive InputConnection
E/flutter ( 5874): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'call' was called on null.
E/flutter ( 5874): Receiver: null
E/flutter ( 5874): Tried calling: call(Instance of 'Place')
E/flutter ( 5874): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
E/flutter ( 5874): #1      _SearchMapPlaceWidgetState._selectPlace (package:search_map_place/src/searchMapPlaceWidget.dart:238:12)
E/flutter ( 5874): <asynchronous suspension>
E/flutter ( 5874): #2      _SearchMapPlaceWidgetState._placeOption.<anonymous closure> (package:search_map_place/src/searchMapPlaceWidget.dart:156:24)
E/flutter ( 5874): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
E/flutter ( 5874): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
E/flutter ( 5874): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:181:24)
E/flutter ( 5874): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:352:11)
E/flutter ( 5874): #7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:264:7)
E/flutter ( 5874): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:450:9)
E/flutter ( 5874): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter ( 5874): #10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:100:11)
E/flutter ( 5874): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 5874): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 5874): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 5874): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 5874): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 5874): #16     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 5874): #17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 5874): #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 5874): #19     _invoke1 (dart:ui/hooks.dart:234:10)
E/flutter ( 5874): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
E/flutter ( 5874): 

```

**Comment by Bernardi23** [comment]
Are you on the latest version of flutter?

**Comment by pratik037** [comment]
> Are you on the latest version of flutter?

Yes, I am on **1.6.3** (*beta* channel)

Still this issue persists.
```
I/flutter ( 6232): The argument you passed for Place is not compatible.
E/flutter ( 6232): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'getGeolocation' was called on null.

```

**Comment by pratik037** [comment]
> > Are you on the latest version of flutter?
> 
> Yes, I am on **1.6.3** (_beta_ channel)
> 
> Still this issue persists.
> 
> ```
> I/flutter ( 6232): The argument you passed for Place is not compatible.
> E/flutter ( 6232): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'getGeolocation' was called on null.
> ```

**Updated**

Some kind of range error it shows.
```
/flutter (27031): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: 0
E/flutter (27031): #0      List.[] (dart:core-patch/growable_array.dart:145:60)
E/flutter (27031): #1      new Geolocation.fromJSON (package:search_map_place/src/geolocation.dart:7:51)
E/flutter (27031): #2      Geocoding.getGeolocation (package:search_map_place/src/geocoding.dart:14:24)
E/flutter (27031): <asynchronous suspension>
E/flutter (27031): #3      Place.geolocation (package:search_map_place/src/place.dart:59:42)
E/flutter (27031): <asynchronous suspension>
E/flutter (27031): #4      _HomePageState.build.<anonymous closure> (package:memories/ui/homepage.dart:56:47)
E/flutter (27031): <asynchronous suspension>
E/flutter (27031): #5      _SearchMapPlaceWidgetState._selectPlace (package:search_map_place/src/searchMapPlaceWidget.dart:238:12)
E/flutter (27031): <asynchronous suspension>
E/flutter (27031): #6      _SearchMapPlaceWidgetState._placeOption.<anonymous closure> (package:search_map_place/src/searchMapPlaceWidget.dart:156:24)
E/flutter (27031): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
E/flutter (27031): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
E/flutter (27031): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:181:24)
E/flutter (27031): #10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:352:11)
E/flutter (27031): #11     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:264:7)
E/flutter (27031): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:450:9)
E/flutter (27031): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter (27031): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:100:11)
E/flutter (27031): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (27031): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (27031): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (27031): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (27031): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (27031): #20     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (27031): #21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (27031): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (27031): #23     _invoke1 (dart:ui/hooks.dart:234:10)
E/flutter (27031): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
```

**Comment by Bernardi23** [comment]
Next version I'll add better error handling. Currently don't have time, but as soon as I do, I'll tell you to update. Then we can see exactly what's going on. 

As of now, you can try to modify the original code of the package and try adding print statements to debug or even error handling to try to understand the error a bit better.

Also, I'd recommend you to use the stable version, because as of now, I haven't tested the package on other versions.

**Comment by pratik037** [comment]
> Next version I'll add better error handling. Currently don't have time, but as soon as I do, I'll tell you to update. Then we can see exactly what's going on.
> 
> As of now, you can try to modify the original code of the package and try adding print statements to debug or even error handling to try to understand the error a bit better.
> 
> Also, I'd recommend you to use the stable version, because as of now, I haven't tested the package on other versions.

Ah okay, I'll try messing with it :rofl:  :100:

**Comment by BKirev** [comment]
@pratik037 I had the same issue. Turned out I have to enable the places API in my Google account. Hopefully this helps!

**Comment by harshaIOT** [comment]
There is an issue with padding. Please help me out 
![Screenshot_1582280057](https://user-images.githubusercontent.com/42435996/75025382-1a024880-54c1-11ea-8449-a23713e1a8c7.png)
![Screenshot 2020-02-21 at 3 38 00 PM](https://user-images.githubusercontent.com/42435996/75025385-1c64a280-54c1-11ea-8282-67014fa96e1f.png)

**Comment by XamMobileDev** [comment]
@harshaIOT Have u resolved the issue .If u resolved can u help me to fix it

**Comment by GerRev** [comment]
also have this issue
