### ISSUE TITLE
The argument you passed for Place is not compatible

### ISSUE THREAD

**Issue by BKirev** [Bernardi23/search_map_place#2]
Hey there!

First of all, thank you for the awesome work! I'm using the lastest version of the plugin and the example provided, but I'm facing this issue:

```
I/flutter ( 8067): The argument you passed for Place is not compatible.
I/flutter ( 8067): Another exception was thrown: NoSuchMethodError: The method 'call' was called on null.
```

This is after I enter something, get a suggestion and click on the search icon.
If I just click on the suggestion, the output is the following:

```
E/flutter ( 8067): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: 0
E/flutter ( 8067): #0      List.[] (dart:core-patch/growable_array.dart:145:60)
E/flutter ( 8067): #1      new Geolocation.fromJSON (package:search_map_place/src/geolocation.dart:7:51)
E/flutter ( 8067): #2      Geocoding.getGeolocation (package:search_map_place/src/geocoding.dart:14:24)
E/flutter ( 8067): <asynchronous suspension>
E/flutter ( 8067): #3      Place.geolocation (package:search_map_place/src/place.dart:59:42)
E/flutter ( 8067): <asynchronous suspension>
E/flutter ( 8067): #4      MapSampleState.build.<anonymous closure> (package:pro_organizer/main.dart:87:49)
E/flutter ( 8067): <asynchronous suspension>
E/flutter ( 8067): #5      _SearchMapPlaceWidgetState._selectPlace (package:search_map_place/src/searchMapPlaceWidget.dart:238:12)
E/flutter ( 8067): <asynchronous suspension>
E/flutter ( 8067): #6      _SearchMapPlaceWidgetState._placeOption.<anonymous closure> (package:search_map_place/src/searchMapPlaceWidget.dart:156:24)
E/flutter ( 8067): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
E/flutter ( 8067): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
E/flutter ( 8067): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:181:24)
E/flutter ( 8067): #10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:352:11)
E/flutter ( 8067): #11     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:264:7)
E/flutter ( 8067): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:450:9)
E/flutter ( 8067): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter ( 8067): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:100:11)
E/flutter ( 8067): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 8067): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 8067): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 8067): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 8067): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 8067): #20     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 8067): #21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 8067): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 8067): #23     _invoke1 (dart:ui/hooks.dart:234:10)
E/flutter ( 8067): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
E/flutter ( 8067): 
```
Any help will be appreciated!

**Comment by BKirev** [comment]
Turns out I have to have geocoding API enabled as well. By doing this the "issue" is resolved :)

**Comment by Bernardi23** [comment]
I guess that's something I have to add to the documentation! Literally have no time for that, so if you want to contribute, feel free to edit the README.md and make a PR
